jobs:
  - name: msbuild
    plan:
    - task: check-dot-net
      config:
        platform: windows
        run:
          path: powershell
          args: 
          - -Command
          - "[System.Runtime.InteropServices.RuntimeEnvironment]::GetSystemVersion()"
    - task: check-msbuild
      config:
        platform: windows
        run:
          path: powershell
          args: 
          - -Command
          - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe /?

          