resources:
  - name: code
    type: git
    source:
      uri: https://github.com/MarcialRosales/dot-net-pcf-workshop
      branch: master
  - name: pipeline
    type: git
    source:
      uri: https://github.com/MarcialRosales/concourse-workshop
      branch: master

jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
      - get: pipeline
    - task: compile
      config:
        platform: windows
        run:
          path: powershell
          args:
          - pipeline\hello-world-win\lab4\build.ps1
          - -mode test -targetFramework 4.6.1                  
        inputs:
        - name: code
        - name: pipeline

          