resources:
  - name: code
    type: git
    source:
      uri: https://github.com/MarcialRosales/concourse-workshop
      branch: master

jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: compile
      config:
        platform: windows
        run:
          path: powershell
          args:
          - lab3/build.ps1
          - -mode test -targetFramework 4.6.1
          dir: code
        inputs:
        - name: code

          