---
jobs:
- name: job-hello-world
  plan:
  - task: print-hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      params:
        MSG: ((GREETING_MSG))
      run:
        path: sh
        args:
          - -c
          - |
            echo "$MSG" > greeting
            cat greeting
